### ISSUE TITLE
Deployment Target 10.10

### ISSUE THREAD

**Issue by spiderr** [sindresorhus/CircularProgress#23]
Given this is a generic library, could the macOS deployment target be reduced to the 10.10 (Yosemite)?

It compiles and runs just fine for 10.10, and allows broader support for applications that support older macOS versions.

(There is one error with 10.9, the oldest version of macOS that supports Swift).

**Comment by sindresorhus** [comment]
I don't see the point in targeting such an old version of macOS. This project is open source, so you can easily change the deployment target if you want. I prefer to keep 10.12 here, however, as that's the oldest system I'm willing to deal with and test for.
