### ISSUE TITLE
Expose a `lineWidth` property

### ISSUE THREAD

**Issue by preetam-jadakar** [sindresorhus/CircularProgress#24]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/sindresorhus/CircularProgress/issues/24)

I tried changing 'lineWidth` and `radius` but it's not working. Please make it configurable.
![Snip20190704_6](https://user-images.githubusercontent.com/32630983/60646960-33835100-9e5a-11e9-8b08-ffb09d0c330c.png)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($50.00)
### Submitted pull Requests
- [#25 Add ability to change lineWidth.](https://issuehunt.io/r/sindresorhus/CircularProgress/pull/25)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/CircularProgress/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment]
You decide the size by setting the frame, instead of setting a radius.

I agree it makes sense to expose `lineWidth`.

It should be an `@IBInspectable` property.
