### ISSUE TITLE
Please make isCancelled KV observable

### ISSUE THREAD

**Issue by klartext79** [sindresorhus/CircularProgress#29]
Could you add 

`willChangeValue(for: \.isCancelled)`

and

`didChangeValue(for: \.isCancelled)`

on line 367 to make isCancelled observeable. The completion onCancelled cannot be set when including in objective-c project. KVO would help to get cancelled state.

Great project!

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/CircularProgress/releases/tag/v2.1.0
