### ISSUE TITLE
Please make @objc available

### ISSUE THREAD

**Issue by klartext79** [sindresorhus/CircularProgress#30]
Hi there,

love your app. Could you please add a few @objc to make public vars available from objective-c code?

Line 4 (necessary)
`@objc public final class CircularProgress`

Line 329 (var example)
`'@objc public var onCancelled: (() -> Void)?'`

etc. for other public vars

It's not necessary for IBInspectable as these are mapped automatically.

**Comment by sindresorhus** [comment]
Sorry, I don't intend to do any changes that don't also benefit Swift. I suggest you fork and do the changes needed and use your fork.
