### ISSUE TITLE
Change progress type from Double to Decimal

### ISSUE THREAD

**Issue by uuttff8** [sindresorhus/CircularProgress#36]
I faced a bug with loss of precision because Double type is used.

Are there any difficulties with transition to Decimal type?

**Comment by sindresorhus** [comment]
The precision inaccuracies of `Double` is not visible to the human eye in a spinner, so I'm curious what exactly the problem is? Can you elaborate?

**Comment by uuttff8** [comment]
In my app updating other UI elements can be done only when progress property is receiving >= 1.0 value, but with loss of precision I get 0.9998... 

If progress property will be Decimal typed then users of this library will not getting bugs.

**Comment by sindresorhus** [comment]
That sounds more like a bug in how you calculate the percentage. Try some rounding.

I don't plan to switch to `Decimal`. None of Apple's APIs, for example, `Progress` accepts a `Decimal`. It's always a `Double`. That's for a reason. Changing to a `Decimal` would also be a huge breaking change.
