### ISSUE TITLE
No such module 'Cocoa'

### ISSUE THREAD

**Issue by fukemy** [sindresorhus/CircularProgress#37]
![Screen Shot 2021-11-29 at 14 10 45](https://user-images.githubusercontent.com/8202437/143823556-3ee1147e-ee27-49ce-b35a-b5276d05de5e.png)
Hi i got this issue when using SPM

**Comment by sindresorhus** [comment]
That looks like the Swift Playgrounds which only supports UIKit. This package is for macOS (AppKit).

**Comment by fukemy** [comment]
sorry i think this project is work for IOS :(
